### ISSUE TITLE
Remove vec3.create

### ISSUE THREAD

**Issue by vorg** [variablestudio/pex-math#13]
it doesn't take args and it's confusing

**Comment by vorg** [comment]
As a response to https://github.com/pex-gl/pex-math/issues/12

**Comment by vorg** [comment]
So i think we kept it consistency as while it doesn't make sense for vec3 where [0, 0, 0] is easier for quat or mat3 it's not so clear.


```javascript
//vec3
function create () {
  return [0, 0, 0]
}

//quat
function create () {
  return [0, 0, 0, 1]
}

//mat3
function create () {
  return [
    1, 0, 0,
    0, 1, 0,
    0, 0, 1
  ]
}
```

**Comment by vorg** [comment]
@dmnsgn any thought on this?

Or should we allow `vec3.create(x, y, z)` but would anybody use it instead of `[x, y, z]`?

**Comment by dmnsgn** [comment]
I'd say:

**Option 1**
- keep it for consistency
- if you allow `vec3.create(x, y, z)` then `mat3.create(a, b, c, d, e, f, g, h, i)` etc should be updated

**Option 2**
Remove the create method in every class and encourage a pattern like `const m = mat3.identity(new Float32Array(9))`

**Comment by vorg** [comment]
I keeping it for consistency. It will also allow switching to typed arrays in the future.
