### ISSUE TITLE
Quaternion .fromUnitVectors addition

### ISSUE THREAD

**Issue by simonharrisco** [variablestudio/pex-math#15]
So there is a useful code that can find the quaternion required to move from 1 normalized unit vector to another. I wrote it from this: [link](http://lolengine.net/blog/2013/09/18/beautiful-maths-quaternion-from-vectors)

```
function fromUnitVectors (a,b) {
  var x = a[0]
  var y = a[1]
  var z = a[2]
  var vx = b[0]
  var vy = b[1]
  var vz = b[2]
  var c = [0,0,0]

  c[0] = y * vz - vy * z
  c[1] = z * vx - vz * x
  c[2] = x * vy - vx * y
  
  var d = a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
  var q = [d,c[0],c[1],c[2]];
  var l = Math.sqrt(q[0]*q[0] + q[1]*q[1] + q[2]*q[2] + q[3]*q[3]);
  q[3] += l;

  return normalize(q)
}
```

**Comment by simonharrisco** [comment]
Oh, is this what fromTo does.... the docs had it with 4 inputs
`quat.fromTo(q, from, to, up)`

I think ive reinvented the wheel here. Ill just just fromTo as I havnt tested this properly

**Comment by vorg** [comment]
The problem is there is no `up` vector in code. But yes it does the same thing.

**Comment by vorg** [comment]
One thing worth mentioning is that `fromUnitVectors` could be a sibling to `fromPositionTarget` which is a better name than `lookAt`.
