### ISSUE TITLE
Addition of vec4.scale

### ISSUE THREAD

**Issue by simonharrisco** [variablestudio/pex-math#17]
Is it used commonly enough to be added, needed it for:
https://github.com/pex-gl/pex-renderer/pull/181

**Comment by vorg** [comment]
@simonharrisco ok make PR and i'll merge it

**Comment by simonharrisco** [comment]
#23

**Comment by dmnsgn** [comment]
@vorg can you push to npm the latest? It's missing the exported vec4.scale.

**Comment by vorg** [comment]
Pushed in pex-math@3.0.0-2
