### ISSUE TITLE
Add mat3.fromTranslationRotationScale

### ISSUE THREAD

**Issue by dmnsgn** [variablestudio/pex-math#20]
Wondering if this should also be part of the pex-math or not (used in pex-renderer to get a matrix from texture transform):
```js
function fromTranslationRotationScale(translation, rotation, scale) {
  const c = Math.cos(rotation)
  const s = Math.sin(rotation)

  return mat3.mult(
    mat3.mult(
      [
        1, 0, 0,
        0, 1, 0,
        translation[0], translation[1], 1
      ],
      [
        c, s, 0,
        -s, c, 0,
        0, 0, 1
      ]
    ),
    [
      scale[0], 0, 0,
      0, scale[1], 0,
      0, 0, 1
    ]
  );
}
```

cc @vorg

**Comment by vorg** [comment]
It’s also used here https://github.com/pex-gl/pex-renderer/blob/master/transform.js in update function but with quaternion. 

Another thing is that from* functions take vec/mat/quat as first param.
